server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ds_product?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    show-sql: true